name: fedoraTests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: kostahka/fedora_latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: CXX=clang++ cmake -B ${{github.workspace}}/build

    - name: Build
      run: CXX=clang++ cmake --build ${{github.workspace}}/build

    - name: Test
      run: make test -C ${{github.workspace}}/build/

