name: MacOSTests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Cache SDL3
      uses: actions/cache@v3
      with:
        path: |
          SDL
        key: macOS-sdl3

    - name: Install SDL3
      run: |
        if ! test -d SDL; then
           git clone https://github.com/libsdl-org/SDL
        fi
        cd SDL
        if ! test -d build; then
            mkdir build
        fi
        cd build
        cmake .. -DSDL_STATIC_PIC=ON -DSDL_SHARED=ON -DSDL_STATIC=ON
        cmake --build .
        sudo cmake --install .

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest 

