name: UbuntuTests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install SDL3
      run: |
        git clone https://github.com/libsdl-org/SDL
        cd SDL
        mkdir build
        cd build
        cmake .. -DSDL_SHARED=ON -DSDL_STATIC=ON
        cmake --build .
        sudo cmake --install .

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest 
      
