name: WindowsTests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install SDL3
      run: |
        git clone https://github.com/libsdl-org/SDL
        mkdir SDL/build
        cmake SDL -B SDL/build -DSDL_SHARED=ON -DSDL_STATIC=ON -DCMAKE_INSTALL_PREFIX=prefix
        cmake --build SDL/build --config ${{env.BUILD_TYPE}} --parallel
        echo "SDL3_DIR=$Env:GITHUB_WORKSPACE/prefix" >> $Env:GITHUB_ENV
        cmake --install SDL/build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
