name: WindowsMinGWTests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          mingw-w64-x86_64-cc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-clang-tools-extra

    - uses: actions/checkout@v3

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Cache SDL3
      uses: actions/cache@v3
      with:
        path: |
          SDL
        key: windowsMinGW-sdl3

    - name: Download SDL3
      run: |
        if ! test -d SDL; then
            git clone https://github.com/libsdl-org/SDL
        fi
        cd SDL
        if ! test -d build; then
            mkdir build
        fi
      shell: bash

    - name: Install SDL3
      run: |
        cmake SDL -B SDL/build -G Ninja -DSDL_STATIC_PIC=ON -DSDL_SHARED=ON -DSDL_STATIC=ON
        cmake --build SDL/build --parallel --verbose
        cmake --install SDL/build
    
    - name: Configure CMake
      run: cmake -B build -G Ninja

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -VV
      shell: bash

